[project]
name = "aws-cdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aws-cdk-lib>=1.200.0",
    "constructs>=10.0.0",
    "jsii>=1.112.0"
]
